### PR TITLE
Added limit-of-detection tensor function

### PR DESCRIPTION
**Pull request by JacksonLChin**
Adds form_limit_tensor to dataImport that returns the limit of detection for each cytokine/subject as a tensor

### CODE REVIEW

**Review by aarmey — APPROVED** [review]
Excellent. Thanks!

So if I follow this, it splits the dataset up by cohort, and then finds the minimum value within the cohort? Occasionally cytokines don't fall below the limit of detection, but this can work for now.

**Comment by aarmey** [comment]
For reference, here are the cohort 3 raw results. Whether the cytokines hit the LoD is separately marked by coloring and an arrow. Unfortunately this isn't carried through into our files.

[20200602_h38-cytokine-panel_MRSA-Cohort3-report.xlsx](https://github.com/meyer-lab/tfac-mrsa/files/7793761/20200602_h38-cytokine-panel_MRSA-Cohort3-report.xlsx)

**Comment by JacksonLChin** [comment]
> Excellent. Thanks!
> 
> So if I follow this, it splits the dataset up by cohort, and then finds the minimum value within the cohort? Occasionally cytokines don't fall below the limit of detection, but this can work for now.

That's correct! Do we have the raw results for Cohort 1 as well? It might make sense to add another file to the repo with these limits of detection.

**Comment by aarmey** [comment]
@scottdtaylor95 do you have this for cohort 1? If not I can ask the group.

**Comment by aarmey** [comment]
I found the original data file we pulled cohort 1 from, and it doesn't have the limit of detection indicated. I'll ask for the a table that includes this.

**Pull request merged**
