### PR TITLE
Figure Reorganizing

### PR DESCRIPTION
**Pull request by JacksonLChin**
Reorganizes figures 4-7, removing obsolete figures and splitting up larger figures into interpretable pieces.

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
I'm not sure I understand what the improvement is here. Why is it better to split the plots across figures? Have you seen figures in papers that are laid out this way?

**Comment by JacksonLChin** [comment]
Still trying to figure out how to layout all the figures--the subjects v. components heatmap is very wide, so combining it with others is difficult. Maybe moving errorbars to figure 4, then all heatmaps to figure 5 would work better?

**Comment by aarmey** [comment]
Hmm... would it be easier to prepare all the figures just using some Illustrator documents, which include plots from here? This would provide easier control over these visual issues. There's no need that we do the paper writing and figure making in Python.

**Comment by JacksonLChin** [comment]
Ceraintly--it might be a bit easier over Illustrator. I'll go ahead and close this PR for now an re-open it once I get a bit more familiar with Illustrator.

**Pull request closed without merging**
