### PR TITLE
Try using QR orthogonalization of subjects matrix

### PR DESCRIPTION
**Pull request by aarmey**

### CODE REVIEW

**Comment by aarmey** [comment]
@cyrillustan any ideas on how to force tensor pack to update here? I keep ending up with version 0.0.2 even though I've updated the pyproject to 0.0.5...

**Comment by cyrillustan** [comment]
> @cyrillustan any ideas on how to force tensor pack to update here? I keep ending up with version 0.0.2 even though I've updated the pyproject to 0.0.5...

Hmm, maybe remove `poetry.lock` and make a new one?

**Comment by aarmey** [comment]
Already tried that...

**Comment by aarmey** [comment]
Seems to be a known issue. https://github.com/python-poetry/poetry/issues/3958

**Pull request closed without merging**
