### PR TITLE
Figure Reformatting

### PR DESCRIPTION
**Pull request by JacksonLChin**
- Reformatted fonts and alignment in figures 2 and 3
 - Moved all model performance results to figure 3
 - Updated predict to return probabilities

### CODE REVIEW

**Comment by JacksonLChin** [comment]
This should update figures 2 and 3--tried to enforce a more paper-like feel.

**Review by aarmey — COMMENTED** [review]
Many plotting defaults are set in figureCommon.py. Perhaps you could change the defaults globally for some of the settings there?

**Comment by JacksonLChin** [comment]
Made some updates to move font sizing to figureCommon--haven't updated plots 5+, though, since they're not being used in the paper at the moment.

**Review by aarmey — APPROVED** [review]
Great

**Pull request merged**
