### PR TITLE
Removed cohort 2 from data import function

### PR DESCRIPTION
**Pull request by JacksonLChin**
- Removes cohort 2 data and patient info prior to normalization

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
This seems to cause a build error in Fig. 3. Perhaps @scottdtaylor95 can take a look.

**Comment by JacksonLChin** [comment]
Sure--if the cohort 2 removal looks fine, I'll go ahead and start re-running the analyses.

**Comment by aarmey** [comment]
There is some per-missingness banding going on again, but yes, try the analysis again. I have a permanent solution for the banding but don't have time to code it up quite yet.

**Comment by aarmey** [comment]
I'm rewriting the data import code because I can't make any sense of what's there.

**Comment by aarmey** [comment]
@scottdtaylor95 actually, my rewrite is turning out to be far more complicated than I expected. Please get this working so we can merge.

**Comment by scottdtaylor95** [comment]
A question on figure 3 - Currently I'm checking correlation of serum and plasma post normalization, this is what we want, right?

**Comment by aarmey** [comment]
Yes

**Comment by scottdtaylor95** [comment]
Should be fixed. Looks like the correlation is basically the same, although the actual values have changed a lot. Also, the cytokines in figure 3 are just 5 random ones. Do we want to change this now? Or after later analysis?

**Comment by aarmey** [comment]
We can change that later.

**Pull request merged**
