### PR TITLE
Added figureS4--cytokine correlaion heatmaps

### LINKED ISSUE #170: Cytokine correlation matrix
One for serum, another for plasma.

### PR DESCRIPTION
**Pull request by JacksonLChin**
Closes #170

### CODE REVIEW

**Review by aarmey — CHANGES_REQUESTED** [review]
This should be the Pearson correlation of the log-transformed values. After that this is ready to merge.

**Comment by JacksonLChin** [comment]
This should swap to the log-transformed Pearson correlation. Doesn't Pearson assume data is normally-distributed? Is that a safe assumption with cytokine data?

**Comment by aarmey** [comment]
This is a common misconception (I even got it on a grant review). Pearson correlation is a measure of linear correlation, it does not assume normality.

**Review by aarmey — CHANGES_REQUESTED** [review]
Why aren't the correlations of a cytokine with itself equal to 1?

**Comment by JacksonLChin** [comment]
Whoops--small bug. I setup correlations so that we wouldn't correlate a cytokine with itself. Just need to modify tick labels slightly.

**Comment by aarmey** [comment]
Great! Thanks.

**Pull request merged**
