### PR TITLE
Added rna_modules for gene expression data

### PR DESCRIPTION
**Pull request by JacksonLChin**
- Added rna_modules.txt.zip
 - Updated dataImport to import module expression instead of raw
 rna data

### CODE REVIEW

**Comment by JacksonLChin** [comment]
@aarmey Here's a PR to update RNA data to use gene modules. I'm getting a weird error with the builds--there's some segmentation fault?

**Comment by aarmey** [comment]
Looking into it...

**Comment by aarmey** [comment]
@JacksonLChin I changed it to import the modules. I can't seem to reproduce that build issue...

**Comment by aarmey** [comment]
This seems to be working. Merging.

**Pull request merged**
