### PR TITLE
Cytokine trim

### PR DESCRIPTION
**Pull request by JacksonLChin**
Removes cytokines with large batch effects

### CODE REVIEW

**Comment by JacksonLChin** [comment]
@aarmey After finding significant differences in cytokine expression across cohorts, I experimented with removing cytokines with large differences in expression. I'm not certain if we want to change the model this late, but this change leads to a large improvement in our validation accuracy.

**Comment by aarmey** [comment]
Hmm... how were these selected as the cytokines to remove?

**Comment by JacksonLChin** [comment]
I used the heatmap I sent in slack earlier--I dropped any cytokine with a large normalized difference across either plasma or serum sources

**Comment by aarmey** [comment]
Ok, let's leave this open until after the discussion with M Yaeman.

One other question about it—Would you say that the interpretation of the persistence-associated components changes, or stays the same?

**Pull request closed without merging**
